pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir('todo_backend') {
                    sh 'docker build -t u6530126/todo-app:latest .'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker push u6530126/todo-app:latest'
                }
            }
        }
    }
}
